#!/bin/sh

usage() {
  cat <<USAGE
usage: git fork submit [-A | -L | <branch_names>...] [-r <remote>] [-q]

Arguments:
  <branch_names>  List of branches to rebase off of master.
                  Defaults to the current branch if not on master.

Options:
  -A              Submits all branches.
  -L              Submits all branches that only exist locally.
  -r <remote>     Remote to push to.
                  Defaults to origin.
  -q              Suppresses output.

USAGE
}

help() {
  usage; cat <<HELP
Ensures <branch_names> are updated, then pushes them to a <remote>.

If <branch_names> are supplied, each branch is rebased off of the fresh master.
You can also instead submit all branches that only exist locally,
or every branch.

HELP
}

cmd_help() {
  help; exit 0
}

cmd_submit(){

  local initial_branch=$(current_branch)
  local remote=''
  local branches=''
  local all_branches=''
  local local_branches=''

  # Until parameter doesn't exist or is an option
  until [ -z "$1" ] || [[ $1 = -* ]]; do
    # add it as a branch name
    branches="$branches $1"; shift
  done

  # If no branches supplied and current is not master, rebase current.
  if [[ -z "$branches" ]] && [[ $initial_branch != 'master' ]]; then
    branches="$initial_branch"
  fi

  parse_opts "$@"

  # If no remote specified, use origin
  if [[ -z "$remote" ]]; then
    remote='origin'
  fi

  # Assert the existance of remote, or fail
  if [[ -n "$(branch_exists $remote)" ]]; then

    # If all_branches is set
    if [ -n "$all_branches" ]; then
      # submit all branches
      for branch in $(branches_matching refs/heads/); do
        submit_branch $branch $remote
      done

    # If local_branches is set
    elif [ -n "$local_branches" ]; then
      # submit all branches that only exist locally
      for branch in $(local_only_branches); do
        submit_branch $branch $remote
      done

    # else if branches were provided or you were on one
    elif [ -n "$branches" ]; then
      # submit those branches
      for branch in $branches; do
        submit_branch $branch $remote
      done
    fi

    # else nothing happens.

    checkout "$initial_branch"
    exit 0

  else
    echo "Remote $remote not found."
    echo 'Please add it to continue.'
    exit 1
  fi

}

parse_opts() {
  while getopts ":ALr:q" option
  do
    case "$option" in
      A)
        all_branches=true
        ;;
      L)
        local_branches=true
        ;;
      r)
        remote="$OPTARG"
        ;;
      q)
        QUIET=true
        ;;
      *)
        usage; exit 1
        ;;
    esac
  done
}
