#!/bin/sh

usage() {
  cat <<USAGE
usage: git fork start <branch_name> [-q|--quiet]

Arguments:
  <branch_name>   A new branch in which to start a contribution.

Options:
  -q | --quiet    Suppresses output.
USAGE
}

help() {
  usage; cat <<HELP
Updates source/master and creates a new branch off of it start a contribution.

HELP
}

cmd_help() {
  help; exit 0
}

cmd_start(){
  # Required first parameter
  BRANCH_NAME=$1; shift

  parse_opts "$@"

  execute "git fork update"
  execute "git checkout -b $BRANCH_NAME"

  exit 0
}

parse_opts() {
  while getopts ":q,quiet" option
  do
    case "$option" in
      q | quiet)
        QUIET=true
        ;;
      *)
        usage; exit 1
        ;;
    esac
  done
}
