#!/bin/sh

usage() {
  cat <<USAGE
usage: git fork start <branch_name> [-q]

Arguments:
  <branch_name>   A new branch in which to start a contribution.

Options:
  -q              Suppresses output.

USAGE
}

help() {
  usage; cat <<HELP
Updates source/master and creates a new branch off of it start a contribution.

HELP
}

cmd_help() {
  help; exit 0
}

cmd_start(){
  # Required first parameter
  local branch_name=$1; shift

  parse_opts "$@"

  execute "git fork update"
  checkout "-b $branch_name"

  exit 0
}

parse_opts() {
  while getopts ":q" option
  do
    case "$option" in
      q)
        QUIET=true
        ;;
      *)
        usage; exit 1
        ;;
    esac
  done
}
