#!/bin/sh

usage() {
  cat <<USAGE
usage: git fork update [-A | -L | <branch_names>...] [-q]

Arguments:
  <branch_names>  List of branches to rebase off of master.
                  Defaults to the current branch if not on master.

Options:
  -A              Updates all branches.
  -L              Updates all branches that only exist locally.
  -q              Suppresses output.

USAGE
}

help() {
  usage; cat <<HELP
Updates local master from source/master.

If <branch_names> are supplied, each branch is rebased off of the fresh master.
You can also instead update all branches that only exist locally (+ master),
or every branch.

HELP
}

cmd_help() {
  help; exit 0
}

cmd_update(){

  local initial_branch=$(current_branch)
  local branches=''
  local all_branches=''
  local local_branches=''

  # Assert the existance of a <source> remote with <master> branch, or fail
  if [[ -n "$(branch_exists 'source master')" ]]; then

    # Until parameter doesn't exist or is an option
    until [ -z "$1" ] || [[ $1 = -* ]]; do
      # add it as a branch name
      branches="$branches $1"; shift
    done

    # If no branches supplied and current is not master, rebase current.
    if [[ -z "$branches" ]] && [[ $initial_branch != 'master' ]]; then
      branches="$initial_branch"
    fi

    parse_opts "$@"

    output 'Updating master from <source>...'
    checkout "master"
    execute "git pull source master"

    # If all_branches is set
    if [ -n "$all_branches" ]; then
      # update all branches
      for branch in $(branches_matching refs/heads/); do
        rebase_branch $branch
      done

    # If local_branches is set
    elif [ -n "$local_branches" ]; then
      # update all branches that only exist locally
      for branch in $(local_only_branches); do
        rebase_branch $branch
      done

    # else if branches were provided or you were on one
    elif [ -n "$branches" ]; then
      # update those branches
      for branch in $branches; do
        rebase_branch $branch
      done
    fi

    # else updating master suffices.

    checkout "$initial_branch"
    exit 0

  else
    echo 'git-fork expects a branch named <master> in a remote named <source>.'
    echo 'Please add one to continue.'
    exit 1
  fi

}

parse_opts() {
  while getopts ":ALq" option
  do
    case "$option" in
      A)
        all_branches=true
        ;;
      L)
        local_branches=true
        ;;
      q)
        QUIET=true
        ;;
      *)
        usage; exit 1
        ;;
    esac
  done
}
