#!/bin/sh

usage() {
  cat <<USAGE
usage: git fork update [<branch_names>... | -L | -A] [-q]

Arguments:
  <branch_names>  List of branches to rebase off of master.
                  Defaults to the current branch if not on master.

Options:
  -A              Updates all branches.
  -L              Updates all branches that only exist locally.
  -q              Suppresses output.

USAGE
}

help() {
  usage; cat <<HELP
Updates local master from source/master.

If <branch_names> are supplied, each branch is rebased off of the fresh master.
You can also instead update all branches that only exist locally (+ master),
or every branch, through the -L and -A flags.

-A overrides -L overrides <branch_names>.

HELP
}

cmd_help() {
  help; exit 0
}

cmd_update(){

  local initial_branch=$(current_branch)
  local branches

  assert_ref_exists 'source/master'

  parse_args "$@"
  parse_opts "$@"

  output 'Updating master from <source>...'
  checkout "master"
  execute "git pull source master"

  for branch in $branches; do
    rebase_branch $branch
  done

  checkout "$initial_branch"
  exit 0

}

parse_args() {
  # Until parameter doesn't exist or is an option
  until [ -z "$1" ] || [[ $1 = -* ]]; do
    # add it as a branch name
    branches="$branches $1"; shift
  done

  # If no branches supplied and current is not master, rebase current.
  if [[ -z "$branches" ]] && [[ $initial_branch != 'master' ]]; then
    branches="$initial_branch"
  fi
}

parse_opts() {
  while getopts ":LAq" option
  do
    case "$option" in
      L)
        branches=$(local_only_branches)
        ;;
      A)
        branches=$(branches_matching refs/heads/)
        ;;
      q)
        QUIET=true
        ;;
      *)
        usage; exit 1
        ;;
    esac
  done
}
