#!/bin/sh

usage() {
  cat <<USAGE
usage: git fork new <source> [<destination>] [-o <origin>]

Arguments:
  <source>        Cloneable URI of the repo you wish to fork.
  <destination>   Directory to clone the fork to.
                  Defaults to the current directory.

Options:
  -o <origin>     URI of a remote to host your fork at.
USAGE
}

help() {
  cat <<HELP
HELP
}

cmd_help() {
  usage; help; exit 0
}

cmd_new(){
  git clone $1 $2
  exit 0
}
